### ISSUE TITLE
Como usuário, gostaria de acessar a página inicial do site

### ISSUE THREAD

**Issue by nekoraw** [vprates-ufmg/TP_Engenharia_de_Software#2]
# Tarefas (a princípio)

- [x] Criar o template base da página inicial. [Matheus]
- [x] Criar rotas básicas do Flask para o uso do template. [Victor]
- [x] Implementar um formulário com caixa de texto básica que envia dados para uma api interna. [Matheus]
- [x] Implementar a api interna e guardar os dados no MongoDB como teste. [Michel]

Deve ser desenvolvido na branch [landing_page](https://github.com/vprates-ufmg/TP_Engenharia_de_Software/tree/landing_page).

**Comment by matheusflavio** [comment]
Finalizado

**Comment by matheusflavio** [comment]
Finalizado
