### ISSUE TITLE
Como usuário, gostaria de marcar uma avaliação anônima como relevante ou não relevante

### ISSUE THREAD

**Issue by nekoraw** [vprates-ufmg/TP_Engenharia_de_Software#6]
# Tarefas (a princípio)
- [x] Criar arte dos botões de vote nas avaliações. [Lucas]
- [x] Implementar os botões de upvote nas publicações. [Matheus]
- [x] Adicionar saldo de upvotes às publicações no banco de dados. [Michel]
- [x] Adicionar vote como uma das possibilidades de ordenação das avaliações. [Victor]

Deve ser desenvolvido na branch [review_relevance_system](https://github.com/vprates-ufmg/TP_Engenharia_de_Software/tree/review_relevance_system).

**Comment by matheusflavio** [comment]
Finalizado

**Comment by matheusflavio** [comment]
Finalizado
